const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const menu=document.getElementById('menu'),hud=document.getElementById('hud'),pause=document.getElementById('pause'),end=document.getElementById('end');
const fileInput=document.getElementById('song'),filename=document.getElementById('filename'),energyEl=document.getElementById('energy'),waveEl=document.getElementById('wave'),styleEl=document.getElementById('style'),timeEl=document.getElementById('time');
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);function resize(){W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape')togglePause()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let audio,source,analyser,data,objectUrl,playing=false,paused=false,startTime=0,elapsed=0,score=0,wave=1,energy=0,spawnClock=0,styleClock=0,shake=0;
const player={x:0,y:0,r:17,vx:0,vy:0,speed:250,dash:0,inv:0};let monsters=[],particles=[],portals=[];
const styles=['ANIME','CARTOON','PAPER','MANGA','GLITCH','REALISTIC','VOID','PIXEL'];const worlds=['FOREST','NEON CITY','DESERT','CANDY','WHITE SPACE','VOID','OLD CARTOON','PAPER CITY'];let currentStyle=0;
fileInput.onchange=()=>{const f=fileInput.files[0];if(!f)return;filename.textContent=f.name;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f)};
document.getElementById('start').onclick=start;document.getElementById('resume').onclick=togglePause;document.getElementById('again').onclick=()=>{end.classList.add('hidden');start()};
function setupAudio(){if(audio)return;audio=new Audio();audio.crossOrigin='anonymous';analyser=new AudioContext().createAnalyser();analyser.fftSize=512;data=new Uint8Array(analyser.frequencyBinCount);source=analyser.context.createMediaElementSource(audio);source.connect(analyser);analyser.connect(analyser.context.destination)}
function start(){setupAudio();menu.classList.add('hidden');end.classList.add('hidden');hud.classList.remove('hidden');reset();if(objectUrl){audio.src=objectUrl;audio.loop=false;audio.play()}else{startSynthetic()}playing=true;startTime=performance.now();requestAnimationFrame(loop)}
function startSynthetic(){const ac=analyser.context;const osc=ac.createOscillator(),gain=ac.createGain();osc.type='sawtooth';osc.frequency.value=110;gain.gain.value=.025;osc.connect(gain).connect(analyser);osc.start();source={stop(){try{osc.stop()}catch(e){}}};}
function reset(){player.x=0;player.y=0;player.inv=0;player.dash=0;monsters=[];particles=[];portals=[];score=0;wave=1;elapsed=0;spawnClock=0;styleClock=0;currentStyle=0;paused=false}
function togglePause(){if(!playing)return;paused=!paused;pause.classList.toggle('hidden',!paused);if(!paused){startTime=performance.now()-elapsed*1000;requestAnimationFrame(loop)}}
function getEnergy(){if(!analyser)return 0;if(data){analyser.getByteFrequencyData(data);let s=0;for(let i=0;i<data.length;i++)s+=data[i];return s/data.length/255}return .25}
function spawnMonster(){const a=Math.random()*Math.PI*2,dist=Math.max(W,H)*.62;monsters.push({x:Math.cos(a)*dist,y:Math.sin(a)*dist,r:14+Math.random()*15,speed:55+energy*120+Math.random()*45,type:Math.floor(Math.random()*4),phase:Math.random()*7})}
function spawnPortal(){const a=Math.random()*Math.PI*2,dist=Math.max(W,H)*.45;portals.push({x:Math.cos(a)*dist,y:Math.sin(a)*dist,t:0})}
function update(dt){elapsed=(performance.now()-startTime)/1000;energy=getEnergy();wave=Math.max(1,Math.floor(elapsed/12)+1);if(elapsed>0&&audio&&!audio.paused&&audio.ended){finish();return}spawnClock-=dt;if(spawnClock<=0){spawnMonster();if(energy>.52&&Math.random()<.5)spawnMonster();spawnClock=Math.max(.22,1.25-energy*1.05)}if(energy>.68&&Math.random()<dt*.7)spawnPortal();
let ax=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),ay=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);let len=Math.hypot(ax,ay)||1;let speed=player.speed*(keys.shift?1.55:1);player.vx=ax/len*speed;player.vy=ay/len*speed;if((keys[' ']||keys.e)&&player.dash<=0){player.vx*=3;player.vy*=3;player.dash=.65;player.inv=.18}player.dash-=dt;player.inv-=dt;player.x+=player.vx*dt;player.y+=player.vy*dt;const bound=Math.min(W,H)*.44;player.x=Math.max(-bound,Math.min(bound,player.x));player.y=Math.max(-bound,Math.min(bound,player.y));
for(const m of monsters){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1;m.x+=dx/d*m.speed*dt;m.y+=dy/d*m.speed*dt;if(d<m.r+player.r&&player.inv<=0){player.inv=.8;score=Math.max(0,score-50);shake=12}}monsters=monsters.filter(m=>Math.hypot(m.x,m.y)<Math.max(W,H)*.85);
for(const p of portals)p.t+=dt;portals=portals.filter(p=>p.t<2.4);for(let i=particles.length-1;i>=0;i--){particles[i].t-=dt;particles[i].x+=particles[i].vx*dt;particles[i].y+=particles[i].vy*dt;if(particles[i].t<=0)particles.splice(i,1)}
styleClock+=dt;if(styleClock>5){styleClock=0;currentStyle=(currentStyle+1)%styles.length}styleEl.textContent=styles[currentStyle];waveEl.textContent=`WAVE ${wave}`;energyEl.style.width=`${Math.round(energy*100)}%`;timeEl.textContent=new Date(elapsed*1000).toISOString().slice(14,19);score+=dt*(energy>.55?2:1)}
function drawWorld(){const e=energy,style=currentStyle;let base=['#10151d','#171126','#d8c8ad','#f8c8e8','#e9f5ff','#171717','#fff','#2b2b36'][style];ctx.fillStyle=base;ctx.fillRect(0,0,W,H);const cx=W/2+player.x*.08,cy=H/2+player.y*.08;
ctx.save();ctx.translate(cx,cy);let grid=45+e*35;ctx.globalAlpha=.12;ctx.strokeStyle='#fff';ctx.lineWidth=1;for(let x=-W;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,-H);ctx.lineTo(x,H);ctx.stroke()}for(let y=-H;y<H;y+=grid){ctx.beginPath();ctx.moveTo(-W,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore();
if(style===4){ctx.globalAlpha=.2;for(let i=0;i<18;i++){ctx.fillStyle=i%2?'#ff39d7':'#00e5ff';ctx.fillRect(Math.random()*W,Math.random()*H,Math.random()*120,2)}}
ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(worlds[(wave-1)%worlds.length],W/2,H-24)}
function draw(){drawWorld();let sx=(Math.random()-.5)*shake,sy=(Math.random()-.5)*shake;shake*=.88;ctx.save();ctx.translate(W/2+sx,H/2+sy);for(const p of portals){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.t*2);ctx.strokeStyle=`rgba(170,80,255,${1-p.t/2.6})`;ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,0,28+Math.sin(p.t*8)*5,48+Math.cos(p.t*7)*7,0,0,Math.PI*2);ctx.stroke();ctx.restore()}for(const m of monsters){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.phase+elapsed*2);let c=m.type===0?'#ff315d':m.type===1?'#8d5cff':m.type===2?'#20e0ff':'#ffcc4d';ctx.shadowBlur=20;ctx.shadowColor=c;ctx.fillStyle='#090912';ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,m.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3;ctx.moveTo(Math.cos(a)*m.r,Math.sin(a)*m.r);ctx.lineTo(Math.cos(a)*(m.r+9+energy*12),Math.sin(a)*(m.r+9+energy*12))}ctx.stroke();ctx.restore()}ctx.shadowBlur=25;ctx.shadowColor='#fff';ctx.fillStyle=player.inv>0?'#ffffff55':'#fff';ctx.beginPath();ctx.arc(player.x,player.y,player.r+energy*5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#9b5cff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x,player.y,player.r+8,0,Math.PI*2);ctx.stroke();ctx.restore()}
function loop(){if(!playing||paused)return;update(1/60);draw();requestAnimationFrame(loop)}function finish(){playing=false;hud.classList.add('hidden');end.classList.remove('hidden');document.getElementById('stats').textContent=`Survived ${Math.floor(elapsed)} seconds · Score ${Math.floor(score)} · Waves ${wave}`}
